/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD4_MAPC;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;
import org.gradle.testfixtures.*;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple functional test for the 'TD4_MAPC.greeting' plugin.
 */
public class TD4_MAPCPluginFunctionalTest {
    private static final String GradleRunner = null;

    @Test
    public void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"), "plugins {" + "  id('TD4_MAPC.greeting')" + "}");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("greeting");
        runner.withProjectDir(projectDir);
        org.gradle.BuildResult result = runner.build();

        // Verify the result
        assertTrue(result.getOutput().contains("Hello from plugin 'TD4_MAPC.greeting'"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
